<?php
define(_NEXT, "<img src=../image/right_arrow.gif>");
define(_PREV, "<img src=../image/back.gif>");
define(_IMGACCOUNT, "<img src=../image/account.png width=15>");
define(_IMGLOGUSER, "<img src=../image/loguser.png width=15>");
define(_IMGLOGDL, "<img src=../image/logdl.png width=15>");
define(_IMGAGENTS, "<img src=../image/agents.png width=15>");
define(_IMGUPLDATA, "<img src=../image/upload_data.png width=15>");
define(_IMGUPLMTLPY, "<img src=../image/upload_multiply.png width=15>");
define(_IMGUPLMOVE, "<img src=../image/upload_movement.png width=15>");
define(_IMGVALIDATE, "<img src=../image/data_valid.png width=15>");
define(_IMGVALIDATEMOVE, "<img src=../image/data_validmove.png width=15>");
define(_IMGMSPOLIS, "<img src=../image/masterpolis.png width=15>");
define(_IMGCOSTUMERS, "<img src=../image/valdata.png width=15>");
define(_IMGPESERTA, "<img src=../image/peserta.png width=15>");
define(_IMGCEKMEDIK, "<img src=../image/cekmedik.png width=15>");
define(_IMGNOTADN, "<img src=../image/sub_hijau.png width=15>");
define(_IMGINVDN, "<img src=../image/pernyataan.png width=15>");
define(_IMGINVDOK, "<img src=../image/invoicedok.png width=15>");
define(_IMGARM, "<img src=../image/sub_merah.png width=15>");
define(_IMGREGARM, "<img src=../image/arm.png width=15>");
define(_IMGUPDDN, "<img src=../image/dn_new.png width=15>");
define(_IMGNOTACN, "<img src=../image/sub_kuning.png width=15>");
define(_IMGDATAMOVE, "<img src=../image/data_move.png width=15>");
define(_IMGKLAIMDIE, "<img src=../image/klaim_meninggal.png width=15>");
define(_IMGKLAIMREFUND, "<img src=../image/refund_premi.png width=15>");
define(_IMGKLAIMREFUND_DTA, "<img src=../image/ref_data.png width=20>");
define(_IMGKLAIMREFUND_VAL, "<img src=../image/ref_validasi.png width=20>");
define(_IMGKLAIMREFUND_CRE, "<img src=../image/ref_create.png width=20>");
define(_IMGMOVERESTRUKTUR, "<img src=../image/restruktur.png width=15>");
define(_IMGMOVERESBIASA, "<img src=../image/restruk_biasa.png width=15>");
define(_IMGMOVERESBALON, "<img src=../image/restruk_balloon.png width=15>");
define(_IMGMOVETOPUP, "<img src=../image/go-top.png width=15>");
define(_IMGCOBDN, "<img src=../image/cob_dn.png width=15>");
define(_IMGCOBCN, "<img src=../image/cob_cn.png width=15>");
?>
